# Generated by Django 3.2.19 on 2023-06-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Наименование работ')),
                ('unit', models.CharField(default='', max_length=5, verbose_name='Ед. изм.')),
                ('price', models.IntegerField(verbose_name='Цена, руб.')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
