# Generated by Django 3.2.19 on 2023-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Наименование работ'),
        ),
    ]
