# Generated by Django 3.2.19 on 2023-06-25 13:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 6, 25, 13, 33, 2, 278817, tzinfo=utc), verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='message',
            field=models.TextField(default='', verbose_name='Сообщение'),
        ),
    ]
