# Generated by Django 3.2.19 on 2023-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abouts',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AddField(
            model_name='abouts',
            name='title',
            field=models.CharField(default='', max_length=60, verbose_name='Заголовок'),
        ),
    ]
