# Generated by Django 3.2.19 on 2023-06-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portlofios',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
